### PR TITLE
Add ort-server repository

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Add the repository for the ort-server with minimal configuration for the initial contribution. All other configuration like branch protection rules will be added after the import.

### CODE REVIEW

**Comment by mnonnenmacher** [comment]
@netomi Can you explain why `auto_init` is removed in the canoncial diff? Is it because the setting is only applied once when the repository is created?

**Comment by netomi** [comment]
That looks like a Bug in the canonical view Wrt properties that are special like auto_init. You can ignore the view for now it was originally a neat idea to show the diff to a minimal config but its deprecated and will be removed when we switch your org to the App mode, when i am back from vacation on wed i will do that.

**Comment by netomi** [comment]
Here is an Exemplare how it will look like https://github.com/eclipse-thingweb/.eclipsefdn/pull/15

**Comment by mnonnenmacher** [comment]
> That looks like a Bug in the canonical view Wrt properties that are special like auto_init. You can ignore the view for now it was originally a neat idea to show the diff to a minimal config but its deprecated and will be removed when we switch your org to the App mode, when i am back from vacation on wed i will do that.

Thanks, IIUC that means that the changes will only be automatically applied after the merge of the PR once you have enabled the app, right?

**Review by mbarbero — APPROVED** [review]

**Comment by mnonnenmacher** [comment]
@mbarbero Thanks for the review, could you also merge and apply the change as mentioned by @netomi?

**Review by heurtematte — APPROVED** [review]

**Comment by heurtematte** [comment]
New repository has been created. Committers will gain access once the sync script runs (~2h).

**Comment by netomi** [comment]
so app mode is now enabled for apoapsis as well, You can find a dashboard at https://otterdog.eclipse.org/index

it will grow over time and give you as much information about your project and its resources as possible.

**Pull request merged**
