### PR TITLE
Configure ort-server repository

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Add some organization settings and configure the ort-server repository.

### CODE REVIEW

**Comment by netomi** [comment]
You should use the pre-defined template functions for creating resources as they define various defaults. I fixed that right away for the PR, can merge as is.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
just out of curiosity as I looked at the commit history of the ort-server repo. In the past there have been no PRs and committers directly pushed to the main branch. With the branch protection rule this is prevented, any change that should go to the main branch will need to go through a PR. So if this is intentional, everything is ok, but just wanted to clarify.

**Comment by mnonnenmacher** [comment]
> You should use the pre-defined template functions for creating resources as they define various defaults. I fixed that right away for the PR, can merge as is.

Thanks for fixing that, I still need to learn more about Otterdog.

> just out of curiosity as I looked at the commit history of the ort-server repo. In the past there have been no PRs and committers directly pushed to the main branch. With the branch protection rule this is prevented, any change that should go to the main branch will need to go through a PR. So if this is intentional, everything is ok, but just wanted to clarify.

It mike look like that because we only imported the Git history instead of moving the repository and use a rebase workflow to keep a linear history and avoid merge commits. But except for the first few commits all changes were done via PRs. We are about to switch development to this repository, that's why I'm now preparing all the settings.

I still need to do a final check if all required settings are there now, but at least the merge queue configuration is missing. What's the process for getting configuration set up that cannot be done via Otterdog, shall I create a Helpdesk ticket?

**Comment by netomi** [comment]
You can find quite useful information about using otterdog here: https://otterdog.readthedocs.io/en/latest/reference/resource-format/

The dashboard for the Eclipse Foundation is available at: https://otterdog.eclipse.org/index where you can also check the configurations of other projects, some already came up with quite amazing things.

We plan to improve the documentation which might be sparse at times and start better communication using discussions at https://github.com/eclipse-csi/otterdog, if you feel something is missing please raise an issue.

**Comment by netomi** [comment]
regarding the merge queue, let me know what you wanna have setup and create either an issue in this repo or via the HelpDesk, then I can set it up accordingly

**Comment by mnonnenmacher** [comment]
> regarding the merge queue, let me know what you wanna have setup and create either an issue in this repo or via the HelpDesk, then I can set it up accordingly.

I have created an issue: https://github.com/eclipse-apoapsis/.eclipsefdn/issues/3

**Pull request merged**
