### PR TITLE
feat: Add Docker jobs to the required checks for ort-server

### PR DESCRIPTION
**Pull request by mnonnenmacher**

### CODE REVIEW

**Comment by netomi** [comment]
something is broken on GitHub side:

> The author ([mnonnenmacher](https://github.com/mnonnenmacher)) of this PR is associated with this organization in the role of CONTRIBUTOR.

thats the second time now.
should be member, we just look at what github is sending us.

will approve manually

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
oh, we use ':' to determine if its a status check coming from an app.

**Comment by netomi** [comment]
ok fixed and applied locally:

```
Project technology.apoapsis[github_id=eclipse-apoapsis] (1/1)

  
  ~ repo_ruleset[name="main", repository=ort-server] {
    ~ required_status_checks     = {
      ~ status_checks              = [
        + "Build Docker Image (:core:generateOpenApiSpec, ui, ui, docker/UI.Dockerfile)"
        + "Build Docker Image (advisor-worker, :workers:advisor:jibDockerBuild)"
        + "Build Docker Image (analyzer-worker-base-image, workers/analyzer/docker, Analyzer.Dockerfile, ana..."
        + "Build Docker Image (config-worker-base-image, workers/config/docker, Config.Dockerfile, config-wo..."
        + "Build Docker Image (core, :core:jibDockerBuild)"
        + "Build Docker Image (evaluator-worker-base-image, workers/evaluator/docker, Evaluator.Dockerfile, ..."
        + "Build Docker Image (kubernetes-jobmonitor, :kubernetes:jobmonitor:jibDockerBuild)"
        + "Build Docker Image (notifier-worker-base-image, workers/notifier/docker, Notifier.Dockerfile, not..."
        + "Build Docker Image (orchestrator, :orchestrator:jibDockerBuild)"
        + "Build Docker Image (reporter-worker-base-image, workers/reporter/docker, Reporter.Dockerfile, rep..."
        + "Build Docker Image (scanner-worker-base-image, workers/scanner/docker, Scanner.Dockerfile, scanne..."
      ~ ]
    ~ }
  ~ }

  Do you want to perform these actions? (Only 'yes' or 'y' will be accepted to approve)

  Enter a value: y

  Applying changes:
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00
  
  Done.
  
  Executed plan: 0 added, 1 changed, 0 live resources ignored.
```

**Comment by mnonnenmacher** [comment]
> oh, we use ':' as a delimiter to determine if its a status check coming from an app. will need to adapt that.

Ok thanks, the ':' is coming from the parameters of the matrix job, I think there is nothing I can do about it.

**Comment by netomi** [comment]
that looks like gradle targets so out of our control certainly, I added a workaround, but this will need to get a better fix to handle all possible status check names.

**Comment by mnonnenmacher** [comment]
> that looks like gradle targets so out of our control certainly, I added a workaround, but this will need to get a better fix to handle all possible status check names.

@netomi This didn't really work out, GitHub is now showing some weird names for the required checks:
image

I figured out that GitHub does not add the matrix parameters if I use them manually to make unqiue job names:
https://github.com/eclipse-apoapsis/ort-server/pull/1643

I will make a PR to update them here.

**Pull request merged**
